import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/**
 * Next.js lint rules for the dashboard.
 *
 * The root config skips this app because Next brings its own rule set,
 * including the accessibility and image checks that only make sense here.
 * `next-env.d.ts` is regenerated by Next on every build and must not be
 * edited, so it is not linted.
 */
const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  { ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'] },
];

export default config;
